### ISSUE TITLE
Setup hard drive size from brooklyn.property

### ISSUE THREAD

**Issue by tbouron** [cloudsoft/jclouds-vcloud-director#15]
Currently, jclouds-vcloud-director does not seem to support the hard drive size initialisation.

As an example, here is how I can setup a 250Go hard drive for AWS inside my `brooklyn.properties`:

```
brooklyn.location.named.<my-location>.templateOptions={mapNewVolumeToDeviceName: ["/dev/sda", 250, true]}
```

Could it be possible to add something similar to be consistent across platforms?

**Comment by andreaturli** [comment]
Thanks @tbouron!

I think it should be possible at least according to this [blog post](http://blogs.vmware.com/vsphere/2012/05/resize-hot-addextend-virtual-machine-disks-using-vcloud-api.html)

**Comment by bostko** [comment]
Now templateOptions have disk property.
You can set `disk: 250` to set the hard disk. Notice that if VM uses fast provisioning it won't work.
Also consider using https://github.com/cloudsoft/brooklyn-blockstore . Its job is to add disks rather than modifying existing ones.
